class State:
    WAITING_POST = 'WAITING_POST'
    EDITING_POST = 'EDITING_POST'
    WAITING_BUTTON_TEXT = 'WAITING_BUTTON_TEXT'
    WAITING_BUTTON_ALERT_TEXT = 'WAITING_BUTTON_ALERT_TEXT'
    WAITING_CORRECT_ANSWER = 'WAITING_RIGHT_ANSWER'
